import re
from calculator import add, subtract
from ollama_client import ask_llm

SYSTEM_PROMPT = """
You are a strict Python code generation engine.
You calculate math operations ONLY by generating algorithmic logic using these two primitive functions:
- add(a, b)
- subtract(a, b)

Rules:
1. Never use raw arithmetic operators (+, -, *, /) or python's eval() to compute expressions.
2. Store the final value inside a variable called result.
3. You can use native Python loops ('for', 'while'), variables, and conditional checks.
4. Output ONLY pure, executable Python code. No text descriptions, no markdown codeblocks, no prose.
5. For multiplication, use a loop with add(). For division, use a loop with subtract(). Resolve negative signs carefully.
"""

def process_prompt(user_prompt: str) -> dict:
   
    # This part is used to filter out non arithmetic prompts 
    if re.search(r'\b(hello|hi+|hey|how are you|good morning)\b', user_prompt, re.I):
        fallback_msg = "Please provide a mathematical operation like addition, subtraction, multiplication, or division."
        return {
            "code": f'result = "{fallback_msg}"',
            "result": fallback_msg
        }

    try:
        # This part checks if the prompt is greeting or not
        generated_code = ask_llm(SYSTEM_PROMPT, user_prompt)
        generated_code = re.sub(r'```python|```', '', generated_code).strip()           # Line stripping to prevent confusion and breaking down of the program


        # This creates a separate space to execute the AI generated code
        safe_globals = {
            # These are the functions that we importing from calculator.py 
            "add": add,
            "subtract": subtract,
            "__builtins__": {"range": range, "abs": abs, "int": int}            # Allowing python to only use these specific things rather than the entire built-in library for security reasons
        }
        safe_locals = {}        # This captures the variables and the result of the code execution

        exec(generated_code, safe_globals, safe_locals)         # This compiles and executes the code generated by the LLM in a safe environment
        

        # This part returns the generated code (logic) and the result 

        if "result" in safe_locals:
            return {
                "code": generated_code,
                "result": str(safe_locals["result"])
            }
            

    # The expectation block if the code generated by the LLM fails to execute or if there is an error in the execution

    except Exception as exc:
        return {
            "code": f"# Execution error fallback\nresult = 'Error during LLM code execution: {exc}'",
            "result": f"Error parsing operation."
        }
    
    # This is the final fallback block if the code generated by the LLM does not contain a 'result' variable or if it fails to execute properly
    return {
        "code": "# Fallback block\nresult = 'Could not parse execution payload'",
        "result": "Error processing calculation."
    }